cart/urls.py
from django.urls import path

from  . import views

app_name= "cart"

urlpatterns = [
   
    path('agregar/<int:producto_id>', views.agregar_producto, name="agregar"),

    path('eliminar/<int:producto_id>', views.eliminar_producto, name="eliminar"),

    path('restar/<int:producto_id>', views.restar_producto, name="restar"),

    path('limpiar/', views.limpiar_carroproducto, name="limpiar"),


    
    


]

megagames/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('juegos/', include('juegos.urls')),

    path('autenticacion/', include('autenticacion.urls')),
    
    path('megagamesApp/', include('megagamesApp.urls')),

    path('cart/', include('cart.urls')),

    path('shop/', include('shop.urls')),

    path('media/shop', include('shop.urls'))

]

shop/urls.py
from django.urls import path

from  shop.views import *


urlpatterns = [
   
    path('', shop, name="Shop"),

   
    
    

]

cart/models.py
from django.db import models

# Create your models here.

shop/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class CategoriaProd(models.Model):
    nombre= models.CharField(max_length=50)
    created = models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name= "categoriaprod"
        verbose_name_plural="categoriasprod"

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre= models.CharField(max_length=50) 
    #autor= models.ForeignKey(User, on_delete=models.CASCADE)
    categorias= models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="shop/", null= True, blank=True)
    precio= models.FloatField()
    cantidad= models.BooleanField()

    created = models.DateTimeField(auto_now_add=True)
    updated= models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name= "Producto"
        verbose_name_plural="Productos"

    def __str__(self):
        return self.nombre 

cart/views.py
from django.shortcuts import render,redirect

from .cart import Cart
from shop.models import Producto


# Create your views here.

def agregar_producto(request,producto_id):
    cart= Cart(request)
    producto= Producto.objects.get(id=producto_id)

    cart.agregar(producto=producto)
    
    return redirect("Shop")



def eliminar_producto(request,producto_id):
    cart= Cart(request)
    producto= Producto.objects.get(id=producto_id)

    cart.eliminar_carrito(producto=producto)
    
    return redirect("Shop")





def restar_producto(request,producto_id):
    cart= Cart(request)
    producto= Producto.objects.get(id=producto_id)

    cart.restar_producto(producto=producto)
    
    return redirect("Shop")


def limpiar_carroproducto(request):
    cart= Cart(request)
    cart.limpiar_carrito()
    
    return redirect("Shop")

shop/views.py
from django.shortcuts import render
from .models import Producto
from . import views
# Create your views here.


def shop(request):

    productos= Producto.objects.all()

    return render(request,"shop/shop.html", {"productos":productos})

shop/templates/cart/widget.html
<table class="table table-bordered" style="
color: rgba(255, 255, 255, 0.7); 
background-color: rgba(18, 82, 140 , 0.8);
font-family:'Helvetica';
margin-left: 10px;">

        <thead>

            <tr>

                <th colspan="3" class="text-center">
                    Carrito Compras

                </th>
                

            </tr>

            <tr>
                <th>Juego</th>
                <th>Cantidad</th>
                <th>Total</th>
            </tr>

        </thead>

        <tbody style="background-color: rgba(56, 106, 157, 0.8);">
            {% if request.session.cart.items %}

                {% for key, value in request.session.cart.items %}
                    <tr class="text-center">

                        <td>{{value.nombre}}</td>
                        <td>{{value.cantidad}}</td>
                        <td>
                            
                            <a href="{% url 'cart:agregar' value.producto_id %}" class="btn btn-sm btn-success" style="
                                background-color: rgba(18, 82, 140 , 0.8);
                                border-color: #1E5B99 ;">+</a>

                            <a href="{% url 'cart:restar' value.producto_id %}" class="btn btn-sm btn-success" style="
                                background-color: rgba(18, 82, 140 , 0.8);
                                border-color: #1E5B99 ;">-</a><br>
                            {{value.precio}} CLP
                        </td>

                    </tr>

                {% endfor %}

            {% else %}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center" 
                        style="
                        color: rgba(255, 255, 255, 0.7); 
                        background-color: rgba(18, 82, 140 , 0.8);
                        font-family:'Helvetica';
                        ">
                            ¡No has agregado productos!
                        </div>

                    </td>
                </tr>
                
            {% endif %}

        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" style="
                color: rgba(255, 255, 255, 0.7); 
                background-color: rgba(18, 82, 140 , 0.8);
                font-family:'Helvetica';
                ">
                    
                    <a href="#" onclick="mostrarMensaje()">Pagar Total: {{ importe_total_carro }} CLP</a>

                    <script>
                    function mostrarMensaje() {
                        alert('¡Gracias por tu compra!');
                    }
                    </script>
                </td>
            </tr>
        </tfoot>
        
            
</table>